### ISSUE TITLE
Inconsistent spell immunity effects

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#43]
There are a few spells which do not take into account spell immunity.

Examples are Bloodfort with Seal upgrade, Tamamo's Amaterasu mana degen and stun, Martial Arts silence proc.

Not sure if these are intended, but other spells such as Gae Bolg AOE and Belle take into account spell immunity when applying the stun.

**Comment by dun1007** [comment]
Bloodfort's drag component is supposed to bypass spell immunity(as with most non-target disposition abilities in the game), but Amaterasu mana leak effect is not.

Martial Arts proc is caused by an autoattack that is not stopped by spell immunity. It should be fine as is since it is on the line of bash effect

**Comment by gelguy** [comment]
I tested a few others: Tamamo's charms on auto-attack, FA's Windblade applies stun and knockback, Lancer 4's Lovespot silences and forces movement.

I think it might be good to indicate those which are intended to pierce spell immunity on the tooltip somewhere so it is easier for people to refer to.

**Comment by gelguy** [comment]
Updated with #84.
