### ISSUE TITLE
Not clear on what -all does

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#72]
I'm not sure what `-all` is doing. I initially thought it gave excess gold above the number you type in to the rest of your allies, but it does not seem to be doing that.

Should be best to clarify.

**Comment by sngweicong** [comment]
-all X gives excess gold to your teammates such that you are always left with at least X or more gold, however the game it is right now, it is possible to end up with less than X because I forgot to take care of a certain scenario which I just gitpushed.
-all is essentially -all 4950, 4950 because at 5000 gold you do not gain 3000 gold at end of round.
-all X does not give gold to people with 4950 (invariant of X) gold or more because we do not want people to cross the threshold and result in them not getting 3000 gold at end of round as well.

the spairs() basically sorts players with <4950gold by gold in decreasing order, and was necessary so the residue could accumulate as you go down the list with people who had fewer gold.

current version kinda works as I have been using it in games I play,

BUT

I pretty much brainfarted with the V2 function because I missed the obvious and should have precomputed using everyone's gold instead of for-looping and deciding teammate-by-teammate on how much to give, I guess I was too anchored on trying to fix the original and utterly malfunctioning DistributeGold(). Will probably do a better one some time soon.

**Comment by sngweicong** [comment]
To add on I believe pre-computing is better because current function gives gold to the guy with the least gold at the very last, while in actual games the ones who really need the gold are the ones with low gold.

**Comment by gelguy** [comment]
So from what I gather, `-all` does not work unless you are above 4950 gold.

`-all (number)` keeps (number) gold for yourself, while distributing the remainder among your team.
Only players below 4950 gold will receive a part of the remainder.
The gold is initially split evenly among the eligible players.
If a player receiving a split portion would be bumped up above 4950, he is instead given gold until he reaches 4950, and the residue is kept.
The next player who can get both the split portion and residue and still be below 4950 will be given such, and the residue is reset to 0. Otherwise he is bumped to 4950, and the remainder added to the residue.

So as you mentioned the person with the least gold may not always receive the most, since the first person eligible for the residue will receive it.

Also to note will be that is the remaining residue disappears, so gold is actually lost.

**Comment by sngweicong** [comment]
You are right on most counts, but in all iterations of the loop, giving gold is done using GiveGold() which will in no scenarios result in lost gold since it is strictly between players, residue merely records the surplus; gold is not "given" to residue.

**Comment by gelguy** [comment]
Ah, I see. The remainder is kept with the player who gave the gold.

Closing this issue then, but I think it should be made clear that `-all` only works if you are above 4950 gold.
